exec: ../dist/build/CodetalkIRC/CodetalkIRC
args:
    - production
host: irc.codetalk.io # This will be used as APPROOT
ssl: false

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
# copy-to: user@host:/opt/keter/incoming

static-hosts:
    - host: irc.codetalk.io/static
      root: ../static # relative to config file, just like the executable
