Default: &defaults
  database: CodetalkIRC.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: CodetalkIRC_test.sqlite3
  <<: *defaults

Staging:
  database: CodetalkIRC_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: CodetalkIRC_production.sqlite3
  poolsize: 100
  <<: *defaults
